### ISSUE TITLE
Improve DurationPicker component

### ISSUE THREAD

**Issue by thegreat-vanderlinde** [vyper-protocol/vyper-otc-ui#124]
We need to improve the `DurationPicker` currently saved here:
https://github.com/vyper-protocol/vyper-otc-ui/blob/dev/src/pages/contract/create/index.tsx#L120-L142

in details we need to:

- [ ] move to a dedicate component file
- [ ] improve the UX in order to allow a more flexible picking, right now with the buttons +/- 5 min is hard to set for example 3h
- [ ] improve the duration preview, now we're using `moment.duration(value, 'milliseconds').humanize()` but that's rendering the same label "one hour" both in case of `1:00` and `1:10` for example.

**Comment by vantessel** [comment]
Ideally one can also choose the duration by specifying the exact date and time. E.g. 7 Oct 2022 10:00 AM instead of 1 day. 

Also when choosing durations, it would make sense for the "settle start" duration (>0) to be counted from "deposit end" and not from now. So e.g. "1m deposit end" and "5m settle start" would be a contract where deposits end in 1 minute from now, and where settlement is available 6 minutes from now
