### ISSUE TITLE
Contract simulator

### ISSUE THREAD

**Issue by thegreat-vanderlinde** [vyper-protocol/vyper-otc-ui#127]
We'll need a contract simulator to simulate PnL changes accordingly to price variations.

This will be similar to bitmex: 
<img width="912" alt="Screenshot 2022-10-06 at 09 56 27" src="https://user-images.githubusercontent.com/91868385/194251030-daa0a592-b673-461c-8c21-13002f8be891.png">

**Comment by vantessel** [comment]
To add some context, this simulator will eventually be in two places, the contract summary page, and the create contract page. 

For the "summary page", it makes sense to have only the "current price" to simulate PnL since that's the only variable (notional, collateral, strike are fixed). Even for different contracts it wont be need more inputs (except in the case where there are multiple underlyings). We should prioritize this one first. 

In the "create page" instead makes sense to simulate any parameters of the contract. So for the forward it would be: notional, strike, settlement price, and collateral amounts for long and short. This can be synched with the input boxes of the create page to make it easier. Also some parameters will change depending on the contract (e.g. a contract different than forward may not have the strike).

The output should be simulated PnL for Long and Short

**Comment by GnosisAssembler** [comment]
> To add some context, this simulator will eventually be in two places, the contract summary page, and the create contract page.
> 
> For the "summary page", it makes sense to have only the "current price" to simulate PnL since that's the only variable (notional, collateral, strike are fixed). Even for different contracts it wont be need more inputs (except in the case where there are multiple underlyings). We should prioritize this one first.
> 
> In the "create page" instead makes sense to simulate any parameters of the contract. So for the forward it would be: notional, strike, settlement price, and collateral amounts for long and short. This can be synched with the input boxes of the create page to make it easier. Also some parameters will change depending on the contract (e.g. a contract different than forward may not have the strike).
> 
> The output should be simulated PnL for Long and Short

I am gonna make a modular component, as flexible as possible in order to be able to embed it in both places, accordingly
