### ISSUE TITLE
Fix tsconfig.json "json-schema" types

### ISSUE THREAD

**Issue by thegreat-vanderlinde** [vyper-protocol/vyper-otc-ui#13]
<img width="692" alt="image" src="https://user-images.githubusercontent.com/91868385/189974019-e9b4f1b9-58c7-451e-9925-84be4cb27e04.png">

**Comment by GnosisAssembler** [comment]
@thegreat-vanderlinde i dont think there is any problem here. Usually `tsconfig.json`, produces some false warnings, because it fails to parse the correct files, because of cache from VS code. 

If this warning, still stands for you, could you provide steps to replicate it? 

Otherwise we can close this.

**Comment by thegreat-vanderlinde** [comment]
with the last project changes this seems solved, we can close it
