### ISSUE TITLE
Fix unfunded wallet deposits

### ISSUE THREAD

**Issue by thegreat-vanderlinde** [vyper-protocol/vyper-otc-ui#136]
Right now an unfunded wallet is able to deposit, receiving a transaction error. We need to prevent the deposit launch 

![image](https://user-images.githubusercontent.com/91868385/194376449-2ba96de6-e3a4-4df9-85fd-bce8c948c2c2.jpeg)

**Comment by Shikhar15606** [comment]
Hi @thegreat-vanderlinde,
Can you please share the page or the steps involved to reproduce this transaction error ??

**Comment by thegreat-vanderlinde** [comment]
Sure, the steps are pretty straight forward:
- user connects a *new* wallet 
- browse a contract in the summary page (via url or the pubkey in the search bar)
- try to deposit 
- he gets the error in the screenshot because he has no enough token to deposit

The correct steps are same as above but with the token airdrop before the deposit. During the airdrop we check first if the [associated token](https://spl.solana.com/associated-token-account) account exists (in case is missing we crate it) then we airdrop 1k tokens. The error above `0xbc4` means that the atoken account doesn't exists.

To fix this we need to disable the deposit button if the users hasn't enough token to fund the contract side or if the atoken account doesn't exists.

**Comment by vantessel** [comment]
Rather than not showing the button , could we simply show a notification saying something like “not enough tokens”?On 7 Oct 2022, at 10:45, thegreat-vanderlinde ***@***.***> wrote:﻿
Sure, the steps are pretty straight forward:

user connects a new wallet
browse a contract in the summary page (via url or the pubkey in the search bar)
try to deposit
he gets the error in the screenshot because he has no enough token to deposit

The correct steps are same as above but with the token airdrop before the deposit. During the airdrop we check first if the associated token account exists (in case is missing we crate it) then we airdrop 1k tokens. The error above 0xbc4 means that the atoken account doesn't exists.
To fix this we need to disable the deposit button if the users hasn't enough token to fund the contract side or if the atoken account doesn't exists.

**Comment by thegreat-vanderlinde** [comment]
The button should be disabled, not hidden. Surely we can add a tooltip on the button with the explanation why the deposit is not available. A notification is the result of an operation but in this case the operation doesn't even have to be launched.

**Comment by thegreat-vanderlinde** [comment]
@Shikhar15606 please let me know if you need support solving this issue

**Comment by Shikhar15606** [comment]
@thegreat-vanderlinde Thanks for the help and the hints you provided earlier. I have added a check if the atoken account doesn't exist.

Currently, I am working on finding out the token amount that will be sufficient for making the transaction. I am thinking about comparing the buyerDepositAmount (Long button in UI) / sellerDepositAmount (Short button) with the number of tokens present in the token account address.

https://github.com/vyper-protocol/vyper-otc-ui/blob/49430846411c8f14b90f041c9f111dec7aeafe8a/src/components/organisms/actionButtons/DepositButton.tsx#L18

I logged out rateStateQuery and got buyerDepositAmount and sellerDepositAmount like this =>

![image](https://user-images.githubusercontent.com/55849211/194936446-5f1101ee-55f5-4d59-b397-92fe743c675b.png)

**Do let me know If I have got something wrong in the above conclusion**

I am currently having one doubt:
When I log the account info of my token address it shows the amount: 2800000000n, But I have 2800 Tokens on my account. Where does this huge number come from and is there a clean way of converting this amount to the number of tokens so that I can compare it later with buyerDepositAmount (Long button in UI) / sellerDepositAmount?

![image](https://user-images.githubusercontent.com/55849211/194938489-2a70651e-6f4b-41e4-8345-5ea4ece6b39c.png)
