### ISSUE TITLE
Improve first JS load size

### ISSUE THREAD

**Issue by thegreat-vanderlinde** [vyper-protocol/vyper-otc-ui#153]
Currently a production build is affected by some huge sizes:
<img width="723" alt="Screenshot 2022-10-10 at 19 33 00" src="https://user-images.githubusercontent.com/91868385/194923066-1b372fa9-5f08-4e14-87a0-abf6824c7340.png">

We need to improve this

**Comment by Shikhar15606** [comment]
![image](https://user-images.githubusercontent.com/55849211/196708216-c6bf776a-188f-4f4b-9a8c-f576d16e9518.png)
Importing all these providers in _app.tsx is the primary cause of increasing the initial js load size, according to me. Initially, I was thinking of dynamic imports but since these providers are necessary i don't think that would be of any help. I am kind of stuck in figuring out a solution.

**Comment by Shikhar15606** [comment]
@thegreat-vanderlinde can you please look at the above comment.

**Comment by thegreat-vanderlinde** [comment]
@Shikhar15606 sorry for coming on this late.

Actually this issue is stale, with this commit a9a22c4193969fb62f6d7638353dc0a4ffe27d2d we moved the token info fetching from the client to the server and this reduced **a lot** the bundle size as you can see:

<img width="811" alt="Screenshot 2022-10-27 at 16 28 10" src="https://user-images.githubusercontent.com/91868385/198314282-527698f3-9e64-433a-80d0-efca60ff8750.png">

The main cause was the `@solana/spl-token-registry` with the mega json inside.

Right now I don't think it's critical to keep investigating on this, closing this issue
