### ISSUE TITLE
Improve explorer data grid UI

### ISSUE THREAD

**Issue by thegreat-vanderlinde** [vyper-protocol/vyper-otc-ui#234]
Currently the explorer is as following:

https://github.com/vyper-protocol/vyper-otc-ui/blob/93511228aaac04860d12647b1878522c91f68a70/src/components/organisms/ExplorerContractDataGrid/ExplorerContractDataGrid.tsx#L179-L181

We have to remove fixed values for height and width and improve overall look and feel.
Grid height should match screen height

**Comment by stevenhansel** [comment]
@thegreat-vanderlinde To give some update on the progress, I did some research on UI/UX regarding displaying data in tables. I guess the problem with the explorer data grid UI is that it has too many columns or that we're displaying too many datas in the table. But, there are several ways of handling that.

When we're thinking from the UX perspective, usually the user that's trying to use the explorer has a task of finding interesting contracts that they want to participate into. In order for the user to do that, it will usually leads to comparing between two or multiple contracts. When we're comparing things, eventually we will focus on several specific data points that we want to compare within each of the contracts that they're interested in. From this conclusion, we can improve the explorer data grid UI in several ways:

- Search & Filter, this is probably the most obvious improvement because when there will be too many contracts, it will be hard to find exactly what the user wants if they paginate one by one. For example, if the user only has a certain budget, they won't care about participating in a smaller/larger contracts.

- Column Pinning, when a user is comparing datas, especially when they scroll in the horizontal axis, it would be pretty easy to get lost on what you're comparing with (because the first few columns are going to fade), we can instead pin the `title`, `name` or the unique identifier columns so the user doesn't forget what they're comparing with.

![Screen Shot 2022-10-26 at 11 50 28](https://user-images.githubusercontent.com/54180475/197937524-46060a7b-a616-4bdc-bfab-841981fcb75e.png)

Example is taken from https://mui.com/x/react-data-grid/column-pinning/

- Control Column Visibility & Column Reordering, This only applies if the table that we're improving has too many columns. After filtering the data, probably the user will start comparing more seriously on the contracts. The problem is that if there are too many columns, the user will have to scroll horizontally all the time and there are chances that they are scrolling because the data points that they want to see are on the most right side because of the ordering of that column or because that column that the user wants to see is being pushed by the other columns that the user don't care about. We can help them in two ways, hide the columns that the user doesn't care, or reorder the columns.

Now, the problem with the implementation of this is that because we're using `@mui/x-data-grid`, some of the features such as column reordering and column pinning are being paywall blocked (you have to use the pro version). After some library digging, i find that `react-table` v8 would be a great replacement because it's unopinionated in terms of the API design. The library gives you a set of hooks and you can plug it into your JSX component, so the styling is still up to us.

Let me know if you have any comments regarding this and also the next steps if you want to change the library or anything else, thanks! 

UI/UX research references:
- https://ux.stackexchange.com/questions/28090/ui-patterns-for-tables-with-many-columns
- https://www.youtube.com/watch?v=s7nvF1PuAWY
- https://ux.stackexchange.com/questions/95855/what-to-do-with-too-many-columns-in-a-table

**Comment by thegreat-vanderlinde** [comment]
Hey @stevenhansel thanks for the thorough analysis, let me give you a couple of feedbacks:


> some of the features such as column reordering and column pinning are being paywall blocked (you have to use the pro version)

we're evaluating to buy the pro version, the mui data grid is quite good in terms of quality and developer experience, imo. Probably in the next days we'll move on with the pro version.

> * Search & Filter, this is probably the most obvious improvement because when there will be too many contracts

That's definitely true, search and filters are some feature planned in the roadmap for the explorer, the mui data grid allow some basic filtering/sorting out of the box, but we're evaluating something more powerful (like filters in the URL, in order to bookmark researches or share link). Surely one step we'll have to take care will be pagination, as of now all the contracts are fetched together, this is obviously not so scalable.

As of now, with this issue, I think we can stick with the improvements regarding the datagrid width and height, in order to take all the available room in the page.
