### ISSUE TITLE
Simulator text

### ISSUE THREAD

**Issue by vantessel** [vyper-protocol/vyper-otc-ui#257]
Let's style P/L as PnL for consistency. Also in the message below the two underlyings are concatenated and formatting is off. We should change the text slightly to "This is the simulated PnL if .... gets to XXX and .... gets to YYY"

![image](https://user-images.githubusercontent.com/19397409/197544475-e142b9ee-bafb-4708-9dde-fff4dc927d63.png)

**Comment by GnosisAssembler** [comment]
@vantessel  with this sentence "This is the simulated PnL if .... gets to XXX and .... gets to YYY", you mean "This is the simulated PnL if Long gets to <Price> and Short gets to  <Price>"

Also, are we going to have 2 input fields? Because the simulator box is intended to have fixed elements, thus fix size. Thats why the styling of the box is off. Right now we have only one input box, in the code. Shall i add a second one?

**Comment by vantessel** [comment]
> Also, are we going to have 2 input fields? Because the simulator box is intended to have fixed elements, thus fix size. Thats why the styling of the box is off. Right now we have only one input box, in the code. Shall i add a second one?

No, the number of input fields are variable depending on the type of redeem logic, for instance `forward` has [one ](https://github.com/vyper-protocol/vyper-otc-ui/blob/dev/src/models/plugins/redeemLogic/RedeemLogicForwardPlugin.ts#L28) while `settled_forward` has [two ](https://github.com/vyper-protocol/vyper-otc-ui/blob/dev/src/models/plugins/redeemLogic/RedeemLogicSettledForwardPlugin.ts#L30)

> "This is the simulated PnL if .... gets to XXX and .... gets to YYY", you mean "This is the simulated PnL if Long gets to and Short gets to "

No, this should refer to the rate feeds descriptions, for instance for the `settled_forward`: "This is the simulated PnL if Current price gets to XXX and Settlement rate gets to YYY"

**Comment by GnosisAssembler** [comment]
Ok super clear. Thanks
