### ISSUE TITLE
buttons precision in create-page

### ISSUE THREAD

**Issue by FedererKK** [vyper-protocol/vyper-otc-ui#461]
up & down buttons in the 'strike' section should be consistent with value precision, for example DOGE and BTC ± 1$ result in a huge % difference, the up and down button should be consistent with the minimum precision value.

![image](https://user-images.githubusercontent.com/22641409/205985468-18153201-a35d-422c-bca5-fb613d95ac0c.png)

**Comment by vantessel** [comment]
that's tricky because it's a CSS property and a not part of the MUI component. In fact [here](https://github.com/mui/material-ui/issues/3578) they discussed about inserting it but ultimately decided against it. Also it's shown only in some browsers (eg I see it on Firefox but not on Chrome). 

To avoid issues I disabled it in every browsers in #475. You will still be able to change using the arrows and it will be always 1, though I see similar behaviour eg on [bitfinex](https://trading.bitfinex.com/t?type=exchange)
