### ISSUE TITLE
Thumbnail for sharing - make it smaller

### ISSUE THREAD

**Issue by solbricklayer** [vyper-protocol/vyper-otc-ui#509]
How can we make this smaller? This is too invasive IMHO

I am not even sure if this is the right repo, is this property set in the frontend?

<img width="527" alt="Screenshot 2022-12-17 at 18 58 48" src="https://user-images.githubusercontent.com/67789073/208255132-9e969ce4-0842-4ba6-9953-04b6c941d055.png">

Ideally i think the best format is something like this
<img width="549" alt="Screenshot 2022-12-17 at 18 59 51" src="https://user-images.githubusercontent.com/67789073/208255221-b55e8c1b-383a-4ef2-a5f2-7080aaa4ee87.png">

and we can use the 16:9 logo below
![4](https://user-images.githubusercontent.com/67789073/208255278-e9f8a111-df78-447c-9df8-f9b2a591995a.png)

cc: @FedererKK

**Comment by thegreat-vanderlinde** [comment]
agree on this, point by point:
- this has been introduced with #471 
- the assets used are declared [here](https://github.com/vyper-protocol/vyper-otc-ui/blob/dev/src/components/templates/Layout/Layout.tsx#L40-L57)

In order to improve this we could surely change the logo used to a 16:9 as suggested but I think we can't change the description only on sharing preview, if we reduce the [description](https://github.com/vyper-protocol/vyper-otc-ui/blob/babac0faee806187e0b388040f89c47f387588b0/src/utils/constants.ts#L2-L3) it'll change everywhere (acceptable too imo). @solbricklayer can you please share an up to date oneliner you're using on the deck?

**Comment by solbricklayer** [comment]
Trade any on-chain derivative in minutes

for the logo, the one above should be 16:9ish - lmk if u need that as well

**Comment by FedererKK** [comment]
Re-opening this to point out that the URL is taking lot of space too, how about closing with 
"Trade now 👉🏻 [LINK](https://staging.demo.otc.vyperprotocol.io/contract/summary/4o9NWYQCxVjD1gKH8ADMAbip7aHiKsUcnD4ugJzfxjQR)"

**Comment by thegreat-vanderlinde** [comment]
> Re-opening this to point out that the URL is taking lot of space too, how about closing with the following?
> 
> "Trade now 👉🏻 [LINK](https://staging.demo.otc.vyperprotocol.io/contract/summary/4o9NWYQCxVjD1gKH8ADMAbip7aHiKsUcnD4ugJzfxjQR)"

unfortunately that's not possible, is telegram/twitter that decide how to show the URL in the preview
